language: node_js
node_js:
    - "4"
    - "5"
    - "6"
before_install: 
    - npm install -g npm@latest
    - npm install -g codeclimate-test-reporter
script:
    - npm run build
    - npm test
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: ae7591a76cde6b5e21bc17832e487f09b7fb5c7f2ae486472f8179cbfffa49c3
